spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:querydsl-practice;IFEXISTS=FALSE;

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
    show-sql: true
  output:
    ansi:
      enabled: always
  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace